version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "username"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - "27017:27017"
    networks:
      - app-network

  flask-app:
    build: .
    container_name: flask-app
    environment:
      MONGODB_USERNAME: "username"
      MONGODB_PASSWORD: "password"
    ports:
      - "5001:5000"
    networks:
      - app-network
    depends_on:
      - mongodb

networks:
  app-network: